#!/bin/bash
#licence GPLv2 ; this scripts designed by IZAMUKARERA 2010.5.6 update 2014.11.21
#exec cmd for rasberry pi
DIR=/www/remote-hand/tmp
EXEC=$DIR/run_cmd
while true 
do
  CT=`ls $DIR/|grep ".pepocmd"`
  if [ -n `echo $CT | wc -l` ];then
    msleep 100 ; I=0
    for CMD in $CT ; do
      CMD=$DIR/$CMD ; mv $CMD $EXEC.$I ; chmod +x $EXEC.$I ; chown root.root $EXEC.$I
      . $EXEC.$I &
      msleep 100
      rm -rf $EXEC.$I ; I=$(($I + 1))
    done
  fi
done
