#!/bin/sh
if [ ENABLE = "DISABLE" ];then
  exit
elif [ "1" != -1 ];then
  [ -e /www/remote-hand/tmp/.di_read_data ] && . /www/remote-hand/tmp/.di_read_data
  [ -z "${di[23]}" ] && exit
  [ "${di[23]}" = "-1" ] && exit
  [ "${di[23]}" != "1" ] && exit
fi
if [ 21 -gt 7 -a 21 -lt 14 ];then
  /usr/local/bin/pepoirkitpost  
elif [ 21 -gt 13 -a 21 -lt 17 ];then
  /usr/local/bin/pepotocoshelp  4 
elif [ 21 -gt 16 -a 21 -lt 27 ];then
  DIR=/www/remote-hand/tmp
  OPENJTALK=/usr/bin/open_jtalk
  TAKMIVOICE="/var/lib/mecab/dic/open-jtalk/naist-jdic -m /usr/share/hts-voice/takumi/takumi_normal.htsvoice"
  USEVOICE=${TAKMIVOICE}
  VOICE_PITCH=0.7
  prog=iot002_auto_act2
  VROOMIAQ=$DIR/${prog}_viaq.wav
  [ -e $VROOMIAQ ] && exit
  ROOMNAME="部屋"
  tIAQROOM=$(cat /www/remote-hand/.di_read_data.json| jq -r .gpio_i2c)
  [ -z "$tIAQROOM" -o "$tIAQROOM" = "1" -o "$tIAQROOM" = "null" ] && exit
  tIAQROOM=$(cat /www/remote-hand/.di_read_data.json| jq -r .gpio_i2c.iaq)
  IAQROOM=$(echo $tIAQROOM| awk '{gsub(/[^0-9\.]+/,"",$0);printf $0}')
  svc -d /www/pepolinux/iaqvoice/
  TALK=${ROOMNAME}"の空気が"${IAQROOM}"で設定値を超えました、直ちに対処して下さい"
  WGETMAIL=/usr/local/bin/pepolinemsgsend
  SUBJECT=$prog
  $WGETMAIL $SUBJECT++$TALK
  echo -n $TALK |$OPENJTALK -r $VOICE_PITCH -x $USEVOICE -ow $VROOMIAQ
  /usr/local/bin/pepocurlupload iot001.local $VROOMIAQ
#  /usr/bin/aplay $VROOMIAQ
  msleep 10000
  /usr/local/bin/pepocurlupload iot02f.local $VROOMIAQ
  msleep 10000
  /usr/local/bin/pepocurlupload iot001.local $VROOMIAQ
  msleep 10000
  /usr/local/bin/pepocurlupload iot02f.local $VROOMIAQ
  msleep 10000
  rm $VROOMIAQ
  svc -u /www/pepolinux/iaqvoice/
#  /usr/local/bin/peposound 4 
elif [ 21 -lt 8 ];then
  /usr/local/bin/pepodioctl 21 4 
fi
