#!/bin/bash
#licence GPLv2 ; this scripts designed by IZAMUKARERA 2008.4.20 update 2022.2.25
LOCKFILE="/www/remote-hand/tmp/LCK..pppchat"
lockfile -3 -r 3 ${LOCKFILE} >/dev/null 2>&1
if [ $? != 0 ];then
  exit -1
else
  echo -en $$ > ${LOCKFILE}
fi

I=""
G=""
msleep 5000
while [ "X$G" != "XOK" ]
do
	echo -en "AT&F\r\n" || exit
	if [ $? != "0" ]; then
		exit
	fi

	msleep 1000
	read -s -n 3 -t 2 I || exit
	if [ $? != "0" ]; then
		exit
	fi
	G=`echo $I|awk '/OK/{print "OK"}'`
done

echo -en "ATD *99***1#\r\n" || exit

#while [ "X$G" != "XCONNECT" ]
#do
#        msleep 5000
#        read -s -n 8 -t 5 I || exit
#        if [ $? != "0" ]; then
#		exit
#	fi
#	G=`echo $I|awk '/CONNECT/{print "CONNECT"}'`
#done

msleep 5000
exec /usr/sbin/pppd $1
